// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from test.proto</summary>
public static partial class TestReflection {

    #region Descriptor
    /// <summary>File descriptor for test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
        get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestReflection() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
                "Cgp0ZXN0LnByb3RvIiIKB1Rlc3RCdWYSCgoCSUQYASABKAUSCwoDVXJsGAIg",
                "ASgJQhoKCWNvbS5wcm90b0INRmlyc3RQcm90b2J1ZmIGcHJvdG8z"));
        descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
            new pbr::FileDescriptor[] { },
            new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
                new pbr::GeneratedClrTypeInfo(typeof(global::TestBuf), global::TestBuf.Parser, new[]{ "ID", "Url" }, null, null, null)
            }));
    }
    #endregion

}
#region Messages
public sealed partial class TestBuf : pb::IMessage<TestBuf> {
    private static readonly pb::MessageParser<TestBuf> _parser = new pb::MessageParser<TestBuf>(() => new TestBuf());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestBuf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
        get { return global::TestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestBuf() {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestBuf(TestBuf other) : this() {
        iD_ = other.iD_;
        url_ = other.url_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestBuf Clone() {
        return new TestBuf(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private int iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ID {
        get { return iD_; }
        set {
            iD_ = value;
        }
    }

    /// <summary>Field number for the "Url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
        get { return url_; }
        set {
            url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
        return Equals(other as TestBuf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestBuf other) {
        if (ReferenceEquals(other, null)) {
            return false;
        }
        if (ReferenceEquals(other, this)) {
            return true;
        }
        if (ID != other.ID) return false;
        if (Url != other.Url) return false;
        return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
        int hash = 1;
        if (ID != 0) hash ^= ID.GetHashCode();
        if (Url.Length != 0) hash ^= Url.GetHashCode();
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
        if (ID != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ID);
        }
        if (Url.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Url);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
        int size = 0;
        if (ID != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
        }
        if (Url.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestBuf other) {
        if (other == null) {
            return;
        }
        if (other.ID != 0) {
            ID = other.ID;
        }
        if (other.Url.Length != 0) {
            Url = other.Url;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
                default:
                    input.SkipLastField();
                    break;
                case 8: {
                    ID = input.ReadInt32();
                    break;
                }
                case 18: {
                    Url = input.ReadString();
                    break;
                }
            }
        }
    }

}

#endregion


#endregion Designer generated code
